name: 🐛 Bug Report
description: Create a report to help us improve
title: '[BUG] '
labels: ['bug', 'needs-triage']
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report
        
        Thank you for reporting a bug! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: textarea
    id: bug-description
    attributes:
      label: 🐛 Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: 🖼️ Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Drag and drop images here...

  - type: input
    id: os
    attributes:
      label: 💻 Operating System
      description: What OS are you running?
      placeholder: e.g. Ubuntu 22.04, Fedora 39, Arch Linux
    validations:
      required: true

  - type: input
    id: qt-version
    attributes:
      label: 🖥️ Qt Version
      description: What version of Qt are you using?
      placeholder: e.g. 6.4.2, 6.6.1
    validations:
      required: true

  - type: input
    id: cmake-version
    attributes:
      label: 🔨 CMake Version
      description: What version of CMake are you using?
      placeholder: e.g. 3.24.0, 3.27.1

  - type: input
    id: app-version
    attributes:
      label: 📦 ninjaUSB-util Version
      description: What version of ninjaUSB-util are you using?
      placeholder: e.g. 1.0.0, latest from main branch
    validations:
      required: true

  - type: textarea
    id: hardware
    attributes:
      label: ⌨️ Hardware Details
      description: Information about your keyboard and BLE devices
      placeholder: |
        - USB Keyboard: [e.g. Logitech K380]
        - BLE Device: [e.g. iPad, Android tablet]
        - Bluetooth Adapter: [e.g. built-in, USB dongle model]

  - type: textarea
    id: logs
    attributes:
      label: 🔍 Logs
      description: Please paste relevant log output here
      placeholder: Run with --verbose --log-level debug and paste output here
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: 📋 Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might be helpful...

  - type: textarea
    id: possible-solution
    attributes:
      label: 🔧 Possible Solution
      description: If you have ideas for fixing this issue, please describe them here.
      placeholder: "Optional: If you have suggestions for how to fix this..."
